CREATE TABLE #PkTest
( Name VARCHAR(5) NOT NULL )

INSERT INTO #PkTest (Name)
VALUES ('A1234')

INSERT INTO #PkTest (Name)
VALUES ('A123 ')

INSERT INTO #PkTest (Name)
VALUES ('A123')

SELECT DISTINCT Name
FROM #PkTest

ALTER TABLE #PkTest
ADD CONSTRAINT [PK_PkTest] PRIMARY KEY CLUSTERED (Name)